[package]
name = "neoterm"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tokio", "advanced"] }
tokio = { version = "1", features = ["full"] }
portable-pty = "0.7"
vte = "0.15.0"
once_cell = "1.19.0"
futures = "0.3"
